### ISSUE TITLE
Add botbuilder-config repository code

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#1]
Add the botbuilder-config repository code and archive the previous version.

**Comment by garypretty** [comment]
@szul would the BotBuilder-Community-tools repo not be more appropriate for this?

**Comment by garypretty** [comment]
Ok cool. Sorry, only had time to glance quickly so far - that's makes perfect sense. Cheers for clarifying.

**Comment by szul** [comment]
Resolved with commit 98075acb9c8b5b664cd0b011580f5a5f454d4a36
