### ISSUE TITLE
Azure Table Storage fails for conversation state

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#13]
The code ported from the Microsoft repo has this issue attached:
https://github.com/Microsoft/botbuilder-js/issues/277

...which seems to be related to this issue as well (for blob storage):
https://github.com/Microsoft/botbuilder-js/issues/314

A recent PR (https://github.com/Microsoft/botbuilder-js/pull/369) fixes it for the blob storage, and we might be able to piggyback off of it for a fix here, but the PR is on hold right now.

**Comment by sgellock** [comment]
the pr just went into master

**Comment by szul** [comment]
@sgellock Thanks for the heads up!
