### ISSUE TITLE
Port Sentiment Middleware to Node

### ISSUE THREAD

**Issue by martinkearn** [BotBuilderCommunity/botbuilder-community-js#14]
Would be great to have a Node version of the .net sentiment middleware (https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Middleware.SentimentAnalysis).

**Comment by MarekLani** [comment]
@martinkearn I will try to publish here the one we've created.

**Comment by szul** [comment]
Resolved with PR #16. NPM package coming soon.
