### ISSUE TITLE
AdaptiveCardPrompt is missing

### ISSUE THREAD

**Issue by kushalbhabra** [BotBuilderCommunity/botbuilder-community-js#160]
Hi, I'm trying to use AdaptiveCardPrompt  but unable to find it under "@botbuildercommunity/dialog-prompts"

Could find only these Prompts
[ 'NumberWithUnitPromptType',
  'NumberWithUnitPrompt',
  'NumberWithTypePromptType',
  'NumberWithTypePrompt',
  'PhoneNumberPrompt',
  'EmailPrompt',
  'InternetProtocolPromptType',
  'InternetProtocolPrompt',
  'SocialMediaPromptType',
  'SocialMediaPrompt',
  'GUIDPrompt' ]

**Comment by szul** [comment]
#161 resolves this. Install `@botbuildercommunity/dialog-prompts` version 1.1.1 and you should be good.
