### ISSUE TITLE
Service error 'Unknown' when attempting to send a (non-reply) message

### ISSUE THREAD

**Issue by penguinsource** [BotBuilderCommunity/botbuilder-community-js#199]
Hi!

I am using the Bot Framework Rest API with Node. I am successfully sending reply messages upon a user sending a message (in MS Teams).

I am now trying to start a conversation, to which the response comes back successful, with a conversation id.
( POST /v3/conversations returns me an id - great!)

Then, I try to send a message to that conversation id and I keep getting Service error 'Unknown'. I have tried everything..

Get token function (works fine)
![image](https://user-images.githubusercontent.com/2596623/96007424-775e5780-0e0c-11eb-8011-3aa713672d36.png)

Create a conversation (works fine)
![image](https://user-images.githubusercontent.com/2596623/96007656-b1c7f480-0e0c-11eb-99fd-c00dfa31d340.png)

Using the conversationId above, send a message (Not working):
![image](https://user-images.githubusercontent.com/2596623/96012082-c1960780-0e11-11eb-8541-5849efeea6c8.png)
![image](https://user-images.githubusercontent.com/2596623/96012131-cf4b8d00-0e11-11eb-82b7-da75fe92378e.png)

I am following the documentation provided:

https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-api-reference?view=azure-bot-service-4.0#create-conversation

Step 1, create a conversation:
![image](https://user-images.githubusercontent.com/2596623/96020735-7cc39e00-0e1c-11eb-983f-59066009e888.png)
![image](https://user-images.githubusercontent.com/2596623/96020754-8220e880-0e1c-11eb-92dd-270b4afd15c3.png)

Step 2, send message using conversation id from above:
![image](https://user-images.githubusercontent.com/2596623/96020790-8cdb7d80-0e1c-11eb-845c-1af8ff58ed70.png)

**Comment by penguinsource** [comment]
Hello world, please halp?

**Comment by szul** [comment]
Is this a question specifically related to this community repository? It looks like you're asking a question about the Bot Framework in general? You might be better served asking it in the Microsoft Bot Builder JS repository.

**Comment by penguinsource** [comment]
Is it this repository (https://github.com/microsoft/BotFramework-Services/issues/260) or another one that you re referring to?

**Comment by szul** [comment]
It looks like Microsoft has assigned some people to look at it, so it's either the correct repo, or they'll transfer it to the correct one.

**Comment by szul** [comment]
@arafattehsin Please close.

**Comment by arafattehsin** [comment]
Closing this issue as it was related to Bot Framework portal within Azure.
