### ISSUE TITLE
Using sendActivities() doesn't preserve order?

### ISSUE THREAD

**Issue by gabriel-souza-omni** [BotBuilderCommunity/botbuilder-community-js#200]
I've found that if I have multiple messages like 
```
messages = [
    {type: "message", text: "Message 1"},
    {type: "message", text: "Message 2"},
    {type: "message", text: "Message 3"}
]
```
and I send them using `context.sendActivities(messages)` they usually arrive out of order in WhatsApp. Inserting a delay activity, like `{type: "delay", value: 2000}` between the messages helps. Is it something to do with the adapter? Has anyone else experienced this? Thanks in advance.

**Comment by iMicknl** [comment]
@gabriel-souza-omni just to be sure, are you using the Twilio WhatsApp adapter?

Using `sendActivities`, messages are sent in order. However since messages are sent asynchronously and one by one, it can happen that they are out of sync... My advice would be to add a delay indeed.

**Comment by gabriel-souza-omni** [comment]
@iMicknl Yes I am using the Twilio WhatsApp adapter. Thanks for the reassuring answer, I was worrying if this solution was a bit of a hack and that something I made was causing the order to not be preserved.
