### ISSUE TITLE
Unable to send messages from botframework to connected twilio whatsapp

### ISSUE THREAD

**Issue by shehaniperera** [BotBuilderCommunity/botbuilder-community-js#204]
The botframework end point receives the message sent through whatsapp. However when trying to pass the message from bot TwilioWhatsAppAdapter.sendActivities(): Activities of type 'trace' aren't supported. Have used the code provided in https://www.npmjs.com/package/@botbuildercommunity/adapter-twilio-whatsapp and tried the same provided in https://github.com/BotBuilderCommunity/botbuilder-community-js/issues/171

**Comment by iMicknl** [comment]
@shehaniperera has this been resolved, since you closed the issue? :)
