### ISSUE TITLE
Adding Node runtime stops transcript logging

### ISSUE THREAD

**Issue by hsachinraj** [BotBuilderCommunity/botbuilder-community-js#207]
I am referring to this [bug](https://github.com/microsoft/BotFramework-Composer/issues/6082). 
While using Bot composer, I noticed that when I add a custom runtime (JS), my bot stops logging of transcripts and state in Blob and CosmosDB. Until I add the runtime, it works fine. 

I don't know if there is anything needed to get this work. I haven't got any response from the Composer team. Hoping someone here would help. Thanks in advance!

**Comment by iMicknl** [comment]
It could be that JS runtime (preview) in Composer doesn't have the same features as the C# runtime yet. Best place to discuss this is the issue you mentioned or StackOverflow.

Since this is not related to any botbuilder-community packages, I wil close the issue here.
