### ISSUE TITLE
Add TSLint to project

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#21]
Suggested by @iMicknl to clean up the code, and make it more uniform. Would align us with the Bot Framework team's usage.

**Comment by iMicknl** [comment]
I will have a look the coming days, if I can PR this. My preference would also be to enforce this using CI/CI via [Azure Pipelines](https://github.com/marketplace/azure-pipelines). Is this something we could setup eventually? To ensure all new PR's are following the code standard and all tests are passed.

**Comment by szul** [comment]
@iMicknl Yes, I want to move away from Travis-CI and do the build/test/release in Azure Pipelines. Do you know if we need to all be on the same tenant to work together in Pipelines, or is it possible to be a team org with different addresses/accounts?
