### ISSUE TITLE
Add TestAdapter and Mocha unit tests

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#22]
Right now tests are simply an example bot that you can run manually. We should incorporate Mocha as the unit test framework, and then use the TestAdapter in the Bot Framework to help run the tests. Examples for the Node.JS usage of the TestAdapter can be found in the Bot Framework source code, as well as some of the libraries tests.

**Comment by wilhen01** [comment]
+1 would be great to see example tests...

**Comment by szul** [comment]
@wilhen01 I have a handful of new packages I'm working on, and will definitely make the tests for them utilize the TestAdapter.

**Comment by wilhen01** [comment]
@szul Superb! Please link them in here when they get pushed 😄

**Comment by rjgmail88** [comment]
Any update here ? I would like to see some examples of unit test cases.

**Comment by wilhen01** [comment]
I'm happy to share the following sample snippet, hopefully useful to others!

```
import {
  TestAdapter,
  MemoryStorage,
  ConversationState,
  UserState
} from 'botbuilder';
import { MyBot } from '../bot';

beforeEach(() => {
  const memoryStorage = new MemoryStorage();

  const conversationState = new ConversationState(memoryStorage);
  const userState = new UserState(memoryStorage);

  this.myBot = new MyBot(conversationState, userState);
});

test('bot greeting', () => {
  const adapter = new TestAdapter(async context => {
    await this.myBot.onTurn(context);
  });

  // have to return the adapter to get promise results back to Jest
  // otherwise failed assertions won't actually fail the test
  return adapter
    .test(`hi`, 'Welcome to the Bot!')
    .assertReply('Would you like to hear a joke?');
});
```

The `MyBot` import shown there is for a toy bot I wrote which greets the user and tells random jokes. I think the code should be self explanatory but feel free to ask questions.

**Comment by szul** [comment]
@rjgmail88 We're doing two things with these modules: 1.) TSLint, 2.) Tests. But we are slowly working through it. Newer modules will have tests built it. @wilhen01's example shows some general usage, and I'm finishing up a book that has a whole chapter on it.

That's the long way of saying we're getting there :)

**Comment by rjgmail88** [comment]
@appriciate your help @szul and @wilhen01 . I was trying to write the test case but, it had some issue where promise response wasn't handled correctly. Here is what I have.

```
const { TestAdapter } = require('botbuilder');
var expect = require('expect.js');
const adapter = new TestAdapter(async (context) => {
    await context.sendActivity(`Hello World`);
});

describe('Testing  LogHelper Logging', function () {
    this.timeout(1000);
    it('Should test log() info logging', function () {
        adapter.send('help')
            .assertReply('Let me help you to fix your daily routine.')
            .then(() => 
            console.log('~~~~~~~~~~~~~~~~~~'));
    });
});
```

Do you guys think we can test adaptive cards, session state data etc with this going forward ?

**Comment by wilhen01** [comment]
@rjgmail88 If you look at the example I've given above, you need to return the adapter in the test for the promise result to actually affect whether the test passes or fails

**Comment by wilhen01** [comment]
So on line 10 of your snippet change `adapter.send('help')` to `return adapter.send('help')`

**Comment by rjgmail88** [comment]
@wilhen01 I don't see _describe_ and _It_ blocks in your test case. Is that something new in mocha where we can just have a test case wrapped in **test** block ? Sorry just trying to understand if I am missing something.

**Comment by wilhen01** [comment]
@rjgmail88 I'm using Jest rather than mocha so the syntax is slightly different. I'm pretty sure that you'll need to return the adapter regardless of which test framework you're using.

**Comment by wilhen01** [comment]
Just checked the documentation - Jest uses `describe` and `test` rather than `describe` and `it`. In Jest the `describe` functions are merely for grouping and test arrangement and serve no functional purpose, so you can just have `test` without describe - I think it's the same in Mocha.

**Comment by rjgmail88** [comment]
@wilhen01 thank you.

**Comment by wilhen01** [comment]
No problem @rjgmail88 😄

**Comment by rjgmail88** [comment]
@wilhen01 one small favor. I rewrote my test case according to yours as follows 

```
const { TestAdapter, MemoryStorage, ConversationState, UserState } = require('botbuilder');
var { ParentBot } = require('./../src/ParentBot');

// beforeEach(function () {
const memoryStorage = new MemoryStorage();
const conversationState = new ConversationState(memoryStorage);
const userState = new UserState(memoryStorage);
const userName = userState.createProperty('user_name_test');
var parentBot = new ParentBot(conversationState, userState);
// });

describe('Testing', () => {
    const adapter = new TestAdapter(async context => {
        await parentBot.onTurn(context);
    });
    return adapter
        .test(`help`, 'Let me help you to fix your daily routine.')
        .assertReply('Let me help you to fix your daily routine.');
});
```

but, it has some issue and trying to figure our where its going wrong. If I comment the assertReply I see  '0 passing (3ms)' in the debug console which mean test didnt run. If you enable assertReply I see following stack trace. Fyi, my bot says 'Let me help you to fix your daily routine' when user types 'help.'

Error:
Debugger attached.
  0 passing (2ms)
base.js:344
(node:22006) UnhandledPromiseRejectionWarning: Error: TestAdapter.assertReply("Let me help you to fix your daily routine."):  Timed out after 3002ms.
warning.js:18
    at Timeout.waitForActivity [as _onTimeout] (/node_modules/botbuilder-core/lib/testAdapter.js:329:32)
    at ontimeout (timers.js:425:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
(node:22006) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
warning.js:18
(node:22006) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a **non-zero exit code.**

**Comment by wilhen01** [comment]
Sorry, I maybe didn't explain my code example sufficiently You don't need the second assertion in your case - the `test` method on TestAdapter is a wrapper around `send` and `assertReply` which both sends a message (arg 1) and asserts the reply that should be received (arg 2). Docs here: https://docs.microsoft.com/en-us/javascript/api/botbuilder-core/testadapter?view=botbuilder-ts-latest

The reason that my example uses `assertReply` separately is to assert a second response from the bot after the first one (i.e. 'Welcome to the Bot!', _then_ 'Would you like to hear a joke?'). You don't need this if your bot only responds once to the 'help' command.

As for the test not running, I'm not sure - I'd suggest googling how to test promises using mocha. Maybe the `return` trick I have used is specific to Jest.

**Comment by rjgmail88** [comment]
@wilhen01 that make sense. I got it working with test() instead send(). and its rocking ! 

Did you test multi turn flow with any of you test cases ? Ex: if dialog is designed like this. I am wondering if we can wrap it one test case. 

[User: hi 
Bot: what is your name ?
User: Sam 
bot: what is your age ?
user: 30 
Bot: where do you live ?
user: US
bot: Welcome Sam in US.](url)

**Comment by wilhen01** [comment]
Yes I checked multi-turn flow - you can chain unlimited `test`/`send`/`assertReply` commands together on the same adaptor and test an entire conversational flow 😄 glad you got it working!

**Comment by rjgmail88** [comment]
Perfect !
