### ISSUE TITLE
Remove Travis files and add build tasks in Azure DevOps

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#44]

**Comment by iMicknl** [comment]
Would be great to have Azure Pipelines configured for a 1.0 release. I saw that `botbuilder-dotnet` is using a develop branch and CI/CD on Azure Pipelines, maybe we can 'steal' their process partly.

What would a definition look like? Something like this?

# Build Pipeline
Trigger: *

Tasks:
- Install Node.js (10.x)
- npm install
- Run lerna (build all packages)
- Run ESLint (all packages)
- Run mocha tests (all packages)

# Release pipeline
Trigger: master (or manual approval?)
Tasks:
- Release to NPM
- Create git tag + release on Github with Changelog

**Comment by szul** [comment]
Yeah, @garypretty created an org for us, I just haven’t had the opportunity to convert the repos and set up the pipelines yet. I’ve been in a bit of a holding pattern for 6 months, but now I’m back to being active enough to knock some issues out and make some changes. I’ll try to get this situated in the next week or so.

**Comment by szul** [comment]
Resolved by #88.
