### ISSUE TITLE
Separate libraries into different modules

### ISSUE THREAD

**Issue by EricDahlvang** [BotBuilderCommunity/botbuilder-community-js#50]
I requested the creators of this mongodb library move it to the BotBuilderCommunity repository.  However, they objected that the community repository does not have everything separated into different modules: https://github.com/botbuilder-contrib/botbuilder-storage-mongodb/issues/10

**Comment by szul** [comment]
@EricDahlvang The decision was made by @garypretty when the community team was formed that we should parallel the Microsoft structure as closely as possible. As such, much like the botbuilder-azure repo contains all storage adapters, we decided to go with a single storage module here.

Personally, I have no problem if @nurih wants to contribute that package as a `botbuilder-storage-mongodb` folder under the `libraries` folder with the other packages.

**Comment by EricDahlvang** [comment]
Thanks!

**Comment by garypretty** [comment]
Yes, totally fine with me.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
