### ISSUE TITLE
Dialog prompts failing tests on 4.3.4 and 4.4

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#57]
For the [botbuilder-dialogs-prompts](https://github.com/BotBuilderCommunity/botbuilder-community-js/tree/master/libraries/botbuilder-dialog-prompts), running the tests throws the following error per dialog prompt:

```
Error: DialogSet.add(): Invalid dialog being added.
      at DialogSet.add (test\node_modules\botbuilder-dialogs\lib\dialogSet.js:190:19)
      at Context.it (test\index.test.js:33:17)
```

The code for these dialog prompts parallels the dialog prompts in the Microsoft repo. Not sure what the failure is coming from. Needs further investigation.

**Comment by szul** [comment]
@benbrown Any insight here would be appreciated.

**Comment by benbrown** [comment]
This might be a package version thing - all of the BOTBUILDER packages should be the same version

**Comment by szul** [comment]
Resolved by #58.

@benbrown Would believe there was an errant `node_modules` folder in the `test` directory that was the conflict. Not even sure how that got there on my local machine. UGH.

**Comment by brunohjs** [comment]
> This might be a package version thing - all of the BOTBUILDER packages should be the same version

Nice!!!
I had the same problem.
My botbuilder-testing package was at version 4.9.0, while botbuilder was at version 4.8.0.
I changed the version of botbuilder-testing to 4.8.0 and it worked!
Thanks!!!

**Comment by Noman-121** [comment]
![image](https://user-images.githubusercontent.com/93207859/235156940-aaaa1f63-74d9-4282-bc54-3fb105d90e45.png)

can anyone help me i am facing this issue while trying to install coreui-react-pro on ms teams personal tab here is version issue but i have try to install some versions of coreui-react-pro version but not working 
package.json file
---------------------------------------------------
 "react": "^16.14.0",
        "react-dom": "^16.14.0",
        "@coreui/react-pro": "^4.7.0",
       
       error
       ------------------------------------------
npm ERR! While resolving: teamsfx-template-tab@0.1.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^16.14.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">=17" from @coreui/react-pro@4.10.0
npm ERR! node_modules/@coreui/react-pro
npm ERR!   @coreui/react-pro@"^4.7.0" from the root project
