### ISSUE TITLE
Add NPM badges to the README table next the repo packages

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#6]
This could also be implemented for the NPM packages in botbuilder-community-tools. There is a module called [badges](https://www.npmjs.com/package/badges) that looks like a lot of people utilize. Open to this or another solution to align the design of the JavaScript/TypeScript projects with the NuGet badges in the dotnet repo.

**Comment by garypretty** [comment]
@szul for the .NET repo we are using a simple URL to define the badge, it's contents and the color of the badge.  We chose to do this manually at this stage as we will only be pushing NuGet updates for individual components when they actually change, as opposed to pushing NuGet packages for everything on every build of master. An example would be https://img.shields.io/badge/NuGet-1.0.39-blue.svg

**Comment by szul** [comment]
Addressed by pull request #7.
