### ISSUE TITLE
Port C# adapters to JS (Alexa, Google, Twitter)

### ISSUE THREAD

**Issue by iMicknl** [BotBuilderCommunity/botbuilder-community-js#60]
Would be nice to have support for Alexa, Google Assistant and Twitter DM for Javascript based bots. 

Tracking issue for the migration:
- [ ] [Alexa Adapter](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Alexa)
- [ ] [Google Adapter](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Google)
- [ ] [Twitter Adapter](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/blob/develop/libraries/Bot.Builder.Community.Adapters.Twitter)

I will try to make some time for this in the coming weeks. @szul are you aware if someone already started working on this?

**Comment by szul** [comment]
@iMicknl It's on the list of things to do, but hasn't been started yet. There is only a console adapter in the `botbuilder-adapters` folder currently. I am working on AI components right now, so if this is something you want to take a stab at, have at it!

**Comment by tvvignesh** [comment]
@iMicknl @szul Would it be possible to give me an idea on any plans to support Google Assistant please? I love Bot Framework - only problem being that I have to rely on Dialogflow as of now for Google Assistant causing unnecessary extra code. Thanks in advance.

**Comment by szul** [comment]
@tvvignesh I think @iMicknl is working on an Alexa one. For Google, I'd have to do a little more investigating, so I can't give you a time frame on that just yet. Commenting here is a good start though because it lets us know that there is interest for when we're prioritizing work, so thanks for that. I'll definitely reach out when I have more details.

**Comment by iMicknl** [comment]
@tvvignesh I don't have a Google Assistant myself, thus I prioritised Alexa for now. My time the coming 6 weeks will be limited, so don't expect anything from me on short term.

You could give it a try yourself, based on the .NET version and the other JavaScript adapters. Otherwise, someone will hopefully have time to port it to JavaScript also.

**Comment by szul** [comment]
Moving this to v2 milestone. If we wait until these are done for v1, we'll be maintaining two code bases for an extensive period. The v1 code already has multiple renamed packages and upgrade. We'll want to integrate that soon.

**Comment by szul** [comment]
Broken out into #114, #115, and #116 so each can be addressed separately.
