### ISSUE TITLE
Adaptive Card to Image middleware

### ISSUE THREAD

**Issue by iMicknl** [BotBuilderCommunity/botbuilder-community-js#65]
Some channels (like experimental WhatsApp) just support images and don’t support Adaptive Cards. It would be great if there was a middleware, which could be used to transform adaptive cards to images for selected channels.

As far as I know, this is something that is be done by default in the Bot Service. However, this isn’t available for the custom adapters. 

Currently, the latest Adaptive Cards package doesn’t offer an AdaptiveCardRenderer to Image API for NodeJS (https://github.com/microsoft/AdaptiveCards/issues/1012), only for C# (https://github.com/Microsoft/AdaptiveCards/issues/930). So it has to be a custom renderer in NodeJS.

**Comment by Kadae** [comment]
Is there a way to improve the image quality on NodeJS? They're so pixelated...

**Comment by iMicknl** [comment]
@Kadae could you share a bit more information? Image quality of which images? And which code are you using to generate images.

**Comment by Kadae** [comment]
@iMicknl I using BotFramework with CardFactory.adaptiveCard() and in Telegram (they're doesn't support Adaptive Cards) platform renders images.

Image quality is very low. This is a problem.

**Comment by iMicknl** [comment]
@Kadae please create an issue at https://github.com/microsoft/BotFramework-Services. This repository is not a Microsoft governed repository, but it is a community effort where open source extensions for Bot Framework are shared.

Your issue is with the Microsoft Bot Service, thus better belongs in the repository mentioned above.
