### ISSUE TITLE
Standardize the .npmignore file

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#75]
Right now--for publishing--we're only ignoring the `node_modules` folder. We should probably ignore other things like example and test folders. Things that a production package doesn't need.

**Comment by szul** [comment]
Thinking node_modules and examples, but what about tests?

**Comment by iMicknl** [comment]
@szul [this](https://stackoverflow.com/a/37421736) is an interesting discussion. Only include the files by using the `files` property could be a nice solution.

**Comment by szul** [comment]
Although I've simplified this in #101. I'm going to leave this issue open a bit longer in case we want to modify it more.
