### ISSUE TITLE
Node version support

### ISSUE THREAD

**Issue by szul** [BotBuilderCommunity/botbuilder-community-js#78]
Does it make sense to list the supported Node version? I had an older version of Node and came across this issue:
https://github.com/BotBuilderCommunity/botbuilder-community-js/pull/63#issuecomment-518003570

...when reviewing @iMicknl's Twilio WhatsApp adapter. My version could have just been too old though.

What is the standard practice?

**Comment by szul** [comment]
I put it in the [Wiki](https://github.com/BotBuilderCommunity/botbuilder-community-js/wiki/Troubleshooting).

**Comment by iMicknl** [comment]
Should we also add it to the `package.json`? https://stackoverflow.com/questions/29349684/how-can-i-specify-the-required-node-js-version-in-package-json

**Comment by szul** [comment]
We can do that.
