### ISSUE TITLE
Keep a changelog

### ISSUE THREAD

**Issue by iMicknl** [BotBuilderCommunity/botbuilder-community-js#83]
Add a changelog to every package, which shows updates and breaking changes according to [Keep a changelog](https://keepachangelog.com/en/1.0.0/) and [semver](https://semver.org/).

Could be used as source for releases on Github etc.

**Comment by szul** [comment]
All packages should have changelogs in them once #99 is merged.

**Comment by szul** [comment]
@iMicknl Should this be closed? All v1 packages have changelogs, and I've put up a [brief wiki page](https://github.com/BotBuilderCommunity/botbuilder-community-js/wiki/CHANGELOG-Best-Practices) to outline this as a contribution requirement. Not sure if you're looking to add anything else to it before closing.
